### ISSUE TITLE
TODO: R package

### ISSUE THREAD

**Issue by wilsoncai1992** [wilsoncai1992/data.adapt.multi.test#4]
- [x] make class check for W to be matrix
- [x] $ sign instead of [[]] for object
- [x] shiny print method alone
- [ ] write suite of unit tests
